# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.1.1

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import giteapy
from giteapy.models.create_email_option import CreateEmailOption  # noqa: E501
from giteapy.rest import ApiException


class TestCreateEmailOption(unittest.TestCase):
    """CreateEmailOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateEmailOption(self):
        """Test CreateEmailOption"""
        # FIXME: construct object with mandatory attributes with example values
        # model = giteapy.models.create_email_option.CreateEmailOption()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
