# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.18.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import giteapy
from giteapy.models.create_push_mirror_option import CreatePushMirrorOption  # noqa: E501
from giteapy.rest import ApiException


class TestCreatePushMirrorOption(unittest.TestCase):
    """CreatePushMirrorOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreatePushMirrorOption(self):
        """Test CreatePushMirrorOption"""
        # FIXME: construct object with mandatory attributes with example values
        # model = giteapy.models.create_push_mirror_option.CreatePushMirrorOption()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
