# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.18.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import giteapy
from giteapy.models.issue_form_field_type import IssueFormFieldType  # noqa: E501
from giteapy.rest import ApiException


class TestIssueFormFieldType(unittest.TestCase):
    """IssueFormFieldType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIssueFormFieldType(self):
        """Test IssueFormFieldType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = giteapy.models.issue_form_field_type.IssueFormFieldType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
