# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.1.1

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import giteapy
from giteapy.models.stop_watch import StopWatch  # noqa: E501
from giteapy.rest import ApiException


class TestStopWatch(unittest.TestCase):
    """StopWatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStopWatch(self):
        """Test StopWatch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = giteapy.models.stop_watch.StopWatch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
