# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.17.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import giteapy
from giteapy.models.node_info_usage import NodeInfoUsage  # noqa: E501
from giteapy.rest import ApiException


class TestNodeInfoUsage(unittest.TestCase):
    """NodeInfoUsage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNodeInfoUsage(self):
        """Test NodeInfoUsage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = giteapy.models.node_info_usage.NodeInfoUsage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
