# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.20.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import giteapy
from giteapy.models.new_issue_pins_allowed import NewIssuePinsAllowed  # noqa: E501
from giteapy.rest import ApiException


class TestNewIssuePinsAllowed(unittest.TestCase):
    """NewIssuePinsAllowed unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNewIssuePinsAllowed(self):
        """Test NewIssuePinsAllowed"""
        # FIXME: construct object with mandatory attributes with example values
        # model = giteapy.models.new_issue_pins_allowed.NewIssuePinsAllowed()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
