# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.1.1

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import giteapy
from giteapy.models.status_state import StatusState  # noqa: E501
from giteapy.rest import ApiException


class TestStatusState(unittest.TestCase):
    """StatusState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatusState(self):
        """Test StatusState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = giteapy.models.status_state.StatusState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
