# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.17.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import giteapy
from giteapy.models.git_service_type import GitServiceType  # noqa: E501
from giteapy.rest import ApiException


class TestGitServiceType(unittest.TestCase):
    """GitServiceType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGitServiceType(self):
        """Test GitServiceType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = giteapy.models.git_service_type.GitServiceType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
