# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.20.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import giteapy
from giteapy.models.markup_option import MarkupOption  # noqa: E501
from giteapy.rest import ApiException


class TestMarkupOption(unittest.TestCase):
    """MarkupOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMarkupOption(self):
        """Test MarkupOption"""
        # FIXME: construct object with mandatory attributes with example values
        # model = giteapy.models.markup_option.MarkupOption()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
