# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.18.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import giteapy
from giteapy.api.activitypub_api import ActivitypubApi  # noqa: E501
from giteapy.rest import ApiException


class TestActivitypubApi(unittest.TestCase):
    """ActivitypubApi unit test stubs"""

    def setUp(self):
        self.api = giteapy.api.activitypub_api.ActivitypubApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_activitypub_person(self):
        """Test case for activitypub_person

        Returns the Person actor for a user  # noqa: E501
        """
        pass

    def test_activitypub_person_inbox(self):
        """Test case for activitypub_person_inbox

        Send to the inbox  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
