# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import giteapy
from giteapy.models.repo_commit import RepoCommit  # noqa: E501
from giteapy.rest import ApiException


class TestRepoCommit(unittest.TestCase):
    """RepoCommit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRepoCommit(self):
        """Test RepoCommit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = giteapy.models.repo_commit.RepoCommit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
