# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.1.1

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class MergePullRequestOption(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'do': 'str',
        'merge_message_field': 'str',
        'merge_title_field': 'str',
        'force_merge': 'bool'
    }

    attribute_map = {
        'do': 'Do',
        'merge_message_field': 'MergeMessageField',
        'merge_title_field': 'MergeTitleField',
        'force_merge': 'force_merge'
    }

    def __init__(self, do=None, merge_message_field=None, merge_title_field=None, force_merge=None):  # noqa: E501
        """MergePullRequestOption - a model defined in Swagger"""  # noqa: E501

        self._do = None
        self._merge_message_field = None
        self._merge_title_field = None
        self._force_merge = None
        self.discriminator = None

        self.do = do
        if merge_message_field is not None:
            self.merge_message_field = merge_message_field
        if merge_title_field is not None:
            self.merge_title_field = merge_title_field
        if force_merge is not None:
            self.force_merge = force_merge

    @property
    def do(self):
        """Gets the do of this MergePullRequestOption.  # noqa: E501


        :return: The do of this MergePullRequestOption.  # noqa: E501
        :rtype: str
        """
        return self._do

    @do.setter
    def do(self, do):
        """Sets the do of this MergePullRequestOption.


        :param do: The do of this MergePullRequestOption.  # noqa: E501
        :type: str
        """
        if do is None:
            raise ValueError("Invalid value for `do`, must not be `None`")  # noqa: E501
        allowed_values = ["merge", "rebase", "rebase-merge", "squash"]  # noqa: E501
        if do not in allowed_values:
            raise ValueError(
                "Invalid value for `do` ({0}), must be one of {1}"  # noqa: E501
                .format(do, allowed_values)
            )

        self._do = do

    @property
    def merge_message_field(self):
        """Gets the merge_message_field of this MergePullRequestOption.  # noqa: E501


        :return: The merge_message_field of this MergePullRequestOption.  # noqa: E501
        :rtype: str
        """
        return self._merge_message_field

    @merge_message_field.setter
    def merge_message_field(self, merge_message_field):
        """Sets the merge_message_field of this MergePullRequestOption.


        :param merge_message_field: The merge_message_field of this MergePullRequestOption.  # noqa: E501
        :type: str
        """

        self._merge_message_field = merge_message_field

    @property
    def merge_title_field(self):
        """Gets the merge_title_field of this MergePullRequestOption.  # noqa: E501


        :return: The merge_title_field of this MergePullRequestOption.  # noqa: E501
        :rtype: str
        """
        return self._merge_title_field

    @merge_title_field.setter
    def merge_title_field(self, merge_title_field):
        """Sets the merge_title_field of this MergePullRequestOption.


        :param merge_title_field: The merge_title_field of this MergePullRequestOption.  # noqa: E501
        :type: str
        """

        self._merge_title_field = merge_title_field

    @property
    def force_merge(self):
        """Gets the force_merge of this MergePullRequestOption.  # noqa: E501


        :return: The force_merge of this MergePullRequestOption.  # noqa: E501
        :rtype: bool
        """
        return self._force_merge

    @force_merge.setter
    def force_merge(self, force_merge):
        """Sets the force_merge of this MergePullRequestOption.


        :param force_merge: The force_merge of this MergePullRequestOption.  # noqa: E501
        :type: bool
        """

        self._force_merge = force_merge

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MergePullRequestOption, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MergePullRequestOption):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
